version: 2.1
jobs:
  pulumi-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Pulumi CLI
          command: |
            curl -fsSL https://get.pulumi.com | sh
            export PATH=$PATH:/root/.pulumi/bin
      - run:
          name: Pulumi Login
          command: |
            export PATH=$PATH:/root/.pulumi/bin
            pulumi login https://app.pulumi.com/
      - run:
          name: Select or initialize Pulumi stack
          command: |
            export PATH=$PATH:/root/.pulumi/bin
            pulumi stack select glowberry-dev-gha-stack || pulumi stack init glowberry-dev-gha-stack
      - run:
          name: Pulumi Preview
          command: |
            export PATH=$PATH:/root/.pulumi/bin
            pulumi preview
      - run:
          name: Pulumi Up
          command: |
            export PATH=$PATH:/root/.pulumi/bin
            pulumi up -y
workflows:
  build-and-deploy-to-koyeb:
    jobs:
      - pulumi-deploy:
          context: PROJECTS
