version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.0.0
jobs:
  pulumi-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - pulumi/login:
          cloud-url: "https://app.pulumi.com/"
      - run:
          name: Select or initialize Pulumi stack
          command: pulumi stack select glowberry-dev-gha-stack || pulumi stack init glowberry-dev-gha-stack
      - run:
          name: Pulumi Preview
          command: pulumi preview
      - run:
          name: Pulumi Up
          command: pulumi up -y
workflows:
  build-and-deploy-to-koyeb:
    jobs:
      - pulumi-deploy:
          context: PROJECTS